const eventData = [
    {
      title: 'John Morgan',
      img: 'https://m.media-amazon.com/images/M/MV5BNGViM2M4NmUtMmNkNy00MTQ5LTk5MDYtNmNhODAzODkwOTJlXkEyXkFqcGdeQXVyMTY1NDY4NTIw._V1_.jpg',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      length: '2 hours',
      genre: 'Drama',
      date: '2022-04-15',
      time: '7:00 PM',
      timeZone: 'EST',
      price: '$20.00',
      location: 'Theater A, XYZ Cinema',
    },
    {
      title: 'Ellie Anderson',
      img: 'https://i.pinimg.com/originals/8d/68/bf/8d68bfea38d50364b8ee105bd6fb45ea.jpg',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      length: '1 hour 45 minutes',
      genre: 'Comedy',
      date: '2022-05-03',
      time: '6:30 PM',
      timeZone: 'PST',
      price: '$15.00',
      location: 'Comedy Central Hall',
    },
    {
      title: 'Nia Adebayo',
      img: 'https://m.media-amazon.com/images/M/MV5BNGZiMDI0MTItOWMxNC00MWFkLTlkZTEtNDZlNzg0NGZjY2E1XkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_.jpg',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      length: '2 hours 30 minutes',
      genre: 'Action',
      date: '2022-05-20',
      time: '8:15 PM',
      timeZone: 'CST',
      price: '$25.00',
      location: 'Action Arena, XYZ Theater',
    },
    {
      title: 'Rigo Louie',
      img: 'https://dbdzm869oupei.cloudfront.net/img/posters/preview/91226.png',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      length: '1 hour 55 minutes',
      genre: 'Thriller',
      date: '2022-06-10',
      time: '7:45 PM',
      timeZone: 'EST',
      price: '$18.00',
      location: 'Thrill Town Hall',
    },
    {
      title: 'Mia Williams',
      img: 'https://www.assignmentx.com/wp-content/uploads/2020/07/GHOSTS-OF-WAR-movie-poster.jpg',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      length: '2 hours 15 minutes',
      genre: 'Sci-Fi',
      date: '2022-06-25',
      time: '8:30 PM',
      timeZone: 'PST',
      price: '$22.00',
      location: 'Sci-Fi Convention Center',
    },
  ];
  
  export default eventData;
  