const sportsEventData = [
    {
      title: 'Basketball Championship',
      img: 'https://marketplace.canva.com/EAFNHT2duJI/1/0/1131w/canva-colorful-illustration-sport-poster-ZjU5Go_UksY.jpg',
      description: 'Witness an intense battle for the championship title in this thrilling badminton game.',
      duration: '2 hours',
      sport: 'Basketball',
      date: '2022-04-15',
      time: '5:00 PM',
      timeZone: 'EST',
      price: '$25.00',
      location: 'Arena A, Sports Complex',
    },
    {
      title: 'Soccer Showdown',
      img: 'https://graphicriver.img.customer.envatousercontent.com/files/274392722/Soccer-190-prw.jpg?auto=compress%2Cformat&q=80&fit=crop&crop=top&max-h=8000&max-w=590&s=d0098de4d4e0718828fb731483e2f00f',
      description: 'Cheer for your favorite soccer team as they face off in an exciting showdown for glory.',
      duration: '1 hour 45 minutes',
      sport: 'Soccer',
      date: '2022-05-03',
      time: '7:30 PM',
      timeZone: 'PST',
      price: '$20.00',
      location: 'Soccer Stadium',
    },
    {
      title: 'MMA Fight Night',
      img: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/mma-fight-night-design-template-fa655f99ce106690baeda44e8adceba6_screen.jpg?ts=1636970458',
      description: 'Experience the adrenaline-pumping action of Mixed Martial Arts in a night filled with intense bouts.',
      duration: '3 hours',
      sport: 'MMA',
      date: '2022-05-20',
      time: '6:45 PM',
      timeZone: 'CST',
      price: '$30.00',
      location: 'MMA Arena, Sports Center',
    },
    {
      title: 'Football Clash',
      img: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/champions-league-2022-final-flyer-template-design-b521e01b5415e6ab1615e1f4252fdcd5_screen.jpg?ts=1653215645',
      description: 'Get ready for a high-energy football match featuring top teams competing for supremacy.',
      duration: '2 hours 15 minutes',
      sport: 'Football',
      date: '2022-06-10',
      time: '8:00 PM',
      timeZone: 'EST',
      price: '$22.00',
      location: 'Football Field, Stadium',
    },
    {
      title: 'Racing Grand Prix',
      img: 'https://i.pinimg.com/564x/04/98/ae/0498ae0efa269050ec9256cfd96b9860.jpg',
      description: 'Feel the speed and excitement as top-notch drivers compete in a thrilling Grand Prix race.',
      duration: '2 hours 30 minutes',
      sport: 'Racing',
      date: '2022-06-25',
      time: '7:15 PM',
      timeZone: 'PST',
      price: '$35.00',
      location: 'Racing Circuit',
    },
  ];
  
export default sportsEventData;
